services:
  web:
    build:
      context: .
    container_name: seculog-web
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://seculog:seculog@db/seculog_db
    depends_on:
      - db
    volumes:
      - .:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:14
    container_name: seculog-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: seculog
      POSTGRES_PASSWORD: seculog
      POSTGRES_DB: seculog_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  test:
    build:
      context: .
    container_name: seculog-test
    environment:
      - DATABASE_URL=postgresql://seculog:seculog@db/seculog_db
      - PYTHONPATH=/code
    volumes:
      - .:/code
    depends_on:
      - db
    command: pytest --tb=short -vv

volumes:
  pgdata:
